apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
  namespace: default
  labels:
    app: dotnet-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      # Target Windows nodes
      nodeSelector:
        kubernetes.io/os: windows
      
      # Tolerate Windows node taint
      tolerations:
      - key: "os"
        operator: "Equal"
        value: "windows"
        effect: "NoSchedule"
      
      containers:
      - name: aspnet-app
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: dotnet-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  # For internal load balancer (private cluster), uncomment:
  # annotations:
  #   service.beta.kubernetes.io/azure-load-balancer-internal: "true"

