apiVersion: apps/v1
kind: Deployment
metadata:
  name: iis-app
  namespace: default
  labels:
    app: iis-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iis-app
  template:
    metadata:
      labels:
        app: iis-app
    spec:
      # Target Windows nodes
      nodeSelector:
        kubernetes.io/os: windows
      
      # Tolerate Windows node taint
      tolerations:
      - key: "os"
        operator: "Equal"
        value: "windows"
        effect: "NoSchedule"
      
      containers:
      - name: iis
        image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2022
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: iis-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: iis-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  # For internal load balancer (private), uncomment:
  # annotations:
  #   service.beta.kubernetes.io/azure-load-balancer-internal: "true"

